spring.application.name=ecoguardia-backend

# ---- Base de datos PostgreSQL ----
# Crea la base de datos antes de arrancar:  CREATE DATABASE ecoguardia;
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/ecoguardia}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

# ---- JPA / Hibernate ----
# update: crea y actualiza las tablas automaticamente segun las entidades
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ---- Servidor ----
server.port=8080
